id: A5D6EE1EE
title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress of the
  Jarung Kashor Stūpa
type: translation
pechas:
- IA703216B
- IE9FF9BFA
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:47:29.329265
  last_modified_at: 2023-01-04 11:47:29.329274
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IA703216B/462B: B4AE
  IE9FF9BFA/B111: B4AE
